/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2024-12-12 06:26:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entidad.*;

public final class AltaClienteAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./MenuAdmin.jsp", Long.valueOf(1733984782229L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("entidad");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Agregar usuario</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"grid-body\">\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction handleForm(event) {\r\n");
      out.write("\t\t\tlet valido = true;\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet errores = document.querySelectorAll(\".error\");\r\n");
      out.write("\t\t\tfor (let i = 0; i < errores.length; i++) {\r\n");
      out.write("\t\t\t\terrores[i].textContent = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Validar campos obligatorios\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet textInputs = document.querySelectorAll(\".input\");\r\n");
      out.write("\t\t\tfor (let i = 0; i < textInputs.length; i++) {\r\n");
      out.write("\t\t\t\tconst id = textInputs[i].id;\r\n");
      out.write("\t\t\t\tconst campo = document.getElementById(id);\r\n");
      out.write("\t\t\t\tif (!campo.value.trim()) {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"error-\" + id).textContent = \"Este campo es obligatorio.\";\r\n");
      out.write("\t\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tconst ID = document.getElementById(\"dni\").value.trim();\r\n");
      out.write("\t\t\tif(ID.length != 8){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-dni\").textContent = \"el DNI debe tener 8 digitos.\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconst cuil = document.getElementById(\"cuil\").value.trim();\r\n");
      out.write("\t\t\tconst cuilRegex = /^\\d{2}-\\d{8}-\\d{1}$/ ;\r\n");
      out.write("\t\t\tif (!cuilRegex.test(cuil)) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-cuil\").textContent = \"El cuil debe estar en formato xx-xxxxxxxx-x\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// Validar Fecha de Nacimiento (mayor a 18 años)\r\n");
      out.write("\t\t\tconst fechaNacimiento = document.getElementById(\"fecha_nacimiento\").value;\r\n");
      out.write("\t\t\tconst hoy = new Date();\r\n");
      out.write("\t\t\tconst fechaMinima = new Date(hoy.getFullYear() - 18,\r\n");
      out.write("\t\t\t\t\thoy.getMonth(), hoy.getDate());\r\n");
      out.write("\t\t\tif (new Date(fechaNacimiento) > fechaMinima) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-fecha-nacimiento\").textContent = \"Debe ser mayor de 18 años.\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Validar Email (formato correcto)\r\n");
      out.write("\t\t\tconst email = document.getElementById(\"email\").value.trim();\r\n");
      out.write("\t\t\tconst emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("\t\t\tif (!emailRegex.test(email)) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-email\").textContent = \"Debe ingresar un email válido.\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Validar Claves (que coincidan)\r\n");
      out.write("\t\t\tconst clave = document.getElementById(\"clave\").value;\r\n");
      out.write("\t\t\tconst claveConf = document.getElementById(\"claveConf\").value;\r\n");
      out.write("\t\t\tif (clave !== claveConf) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-claveConf\").textContent = \"Las claves no coinciden.\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\treturn valido;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

   // Validar sesion
    Cookie[] cookies = request.getCookies();
    
    String username = null;
    String userID = null;
    String role = null;
    
    if (cookies != null) {
        for (Cookie cookie : cookies) {
            if ("username".equals(cookie.getName())) {
                username = cookie.getValue();
            } else if ("userID".equals(cookie.getName())) {
                userID = cookie.getValue();
            } else if ("role".equals(cookie.getName())) {
                role = cookie.getValue();
            }
        }
    }
    if (username == null || userID == null || role == null || !"Admin".equals(role)) {
        response.sendRedirect("Login.jsp"); 
        return;
    }


      out.write("\r\n");
      out.write("<section class=\"menu\">\r\n");
      out.write("    <navbar>\r\n");
      out.write("        <a href=\"AltaClienteAdmin.jsp\">Agregar Cliente</a>\r\n");
      out.write("        <a href=\"AltaCuentaAdmin.jsp\">Agregar Cuenta</a>\r\n");
      out.write("        <a href=\"ServletCliente?Param=listarClientes\">ABML Clientes</a>\r\n");
      out.write("        <a href=\"ServletCuenta?Param=listarCuentas\">ABML Cuentas</a>\r\n");
      out.write("        <a href=\"ServletPrestamo?Param=listarPrestamos\">Listado Prestamos</a>\r\n");
      out.write("        <a href=\"ServletEstadistico\">Informes estadísticos</a>\r\n");
      out.write("    </navbar>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t<p> ");
      out.print( role + "  -  " + username );
      out.write(" </p>\r\n");
      out.write("    \t<a href=\"ServletSesion\">Cerrar Sesion</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("\t<main>\r\n");
      out.write("\t<h1>Agregar usuario</h1>\r\n");
      out.write("\t<form action=\"ServletCliente\" method=\"post\"\r\n");
      out.write("\t\tonsubmit=\"return handleForm(event)\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"dni\">DNI:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"number\" id=\"dni\" name=\"txtDni\">\r\n");
      out.write("\t\t\t\t\t<span class=\"error\" id=\"error-dni\" style=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"cuil\">CUIL:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"text\" id=\"cuil\" name=\"txtCuil\">\r\n");
      out.write("\t\t\t\t\t<span class=\"error\" id=\"error-cuil\" style=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"nombre\">Nombre:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"text\" id=\"nombre\"\r\n");
      out.write("\t\t\t\t\tname=\"txtNombre\"> <span class=\"error\" id=\"error-nombre\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"apellido\">Apellido:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"text\" id=\"apellido\"\r\n");
      out.write("\t\t\t\t\tname=\"txtApellido\"> <span class=\"error\" id=\"error-apellido\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"sexo\">Sexo:</label></td>\r\n");
      out.write("\t\t\t\t<td><label for=\"M\"> <input type=\"radio\" checked id=\"M\"\r\n");
      out.write("\t\t\t\t\t\tname=\"txtSexo\" value=\"M\"> Hombre\r\n");
      out.write("\t\t\t\t</label> <label for=\"F\"> <input type=\"radio\" id=\"F\" name=\"txtSexo\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"F\"> Mujer\r\n");
      out.write("\t\t\t\t</label></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"fecha_nacimiento\">Fecha de Nacimiento:</label></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"date\" id=\"fecha_nacimiento\"\r\n");
      out.write("\t\t\t\t\tname=\"txtFecha_Nacimiento\"> <span class=\"error\"\r\n");
      out.write("\t\t\t\t\tid=\"error-fecha-nacimiento\" style=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"nacionalidad\">Nacionalidad:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"text\" id=\"nacionalidad\"\r\n");
      out.write("\t\t\t\t\tname=\"txtNacionalidad\"> <span class=\"error\"\r\n");
      out.write("\t\t\t\t\tid=\"error-nacionalidad\" style=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"provincia\">Provincia:</label></td>\r\n");
      out.write("\t\t\t\t<td><select class=\"input\" id=\"provincia\" name=\"ddlProvincia\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"\" selected disabled>Seleccione una\r\n");
      out.write("\t\t\t\t\t\t\tprovincia</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Buenos Aires\">Buenos Aires</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Catamarca\">Catamarca</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Chaco\">Chaco</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Chubut\">Chubut</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Córdoba\">Córdoba</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Corrientes\">Corrientes</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Entre Ríos\">Entre Ríos</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Formosa\">Formosa</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Jujuy\">Jujuy</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"La Pampa\">La Pampa</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"La Rioja\">La Rioja</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Mendoza\">Mendoza</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Misiones\">Misiones</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Neuquén\">Neuquén</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Río Negro\">Río Negro</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Salta\">Salta</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"San Juan\">San Juan</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"San Luis\">San Luis</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Santa Cruz\">Santa Cruz</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Santa Fe\">Santa Fe</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Santiago del Estero\">Santiago del Estero</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Tierra del Fuego\">Tierra del Fuego</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"Tucumán\">Tucumán</option>\r\n");
      out.write("\t\t\t\t</select> <span class=\"error\" id=\"error-provincia\" style=\"color: red;\"></span>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"localidad\">Localidad:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"text\" id=\"localidad\"\r\n");
      out.write("\t\t\t\t\tname=\"txtLocalidad\"> <span class=\"error\"\r\n");
      out.write("\t\t\t\t\tid=\"error-localidad\" style=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"direccion\">Dirección:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"text\" id=\"direccion\"\r\n");
      out.write("\t\t\t\t\tname=\"txtDireccion\"> <span class=\"error\"\r\n");
      out.write("\t\t\t\t\tid=\"error-direccion\" style=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"email\">Email:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"email\" id=\"email\"\r\n");
      out.write("\t\t\t\t\tname=\"txtEmail\"> <span class=\"error\" id=\"error-email\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"telefono\">Teléfono:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"text\" id=\"telefono\"\r\n");
      out.write("\t\t\t\t\tname=\"txtTelefono\"> <span class=\"error\" id=\"error-telefono\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"usuario\">Usuario:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"text\" id=\"usuario\"\r\n");
      out.write("\t\t\t\t\tname=\"txtUsuario\"> <span class=\"error\" id=\"error-usuario\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"clave\">Clave:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"password\" id=\"clave\"\r\n");
      out.write("\t\t\t\t\tname=\"txtClave\"> <span class=\"error\" id=\"error-clave\"\r\n");
      out.write("\t\t\t\t\tstyle=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><label for=\"claveConf\">Confirmar Clave:</label></td>\r\n");
      out.write("\t\t\t\t<td><input class=\"input\" type=\"password\" id=\"claveConf\"\r\n");
      out.write("\t\t\t\t\tname=\"txtClaveConf\"> <span class=\"error\"\r\n");
      out.write("\t\t\t\t\tid=\"error-claveConf\" style=\"color: red;\"></span></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" name=\"btnAceptar\">Agregar Usuario</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t");

		Respuesta res = (Respuesta) request.getAttribute("EstadoCliente");
		if (res != null) {
	
      out.write(" <br>\r\n");
      out.write("\t<p style=\"color: ");
      out.print(res.isEstado() ? "green" : "red");
      out.write("\">\r\n");
      out.write("\t\t");
      out.print(res.getMensaje());
      out.write("</p>\r\n");
      out.write("\t");

		}
	
      out.write(" </main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
