/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2024-12-12 05:09:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import entidad.*;

public final class AltaPrestamoUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./MenuUsuario.jsp", Long.valueOf(1733963303679L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("entidad");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Solicitar Prestamo</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"grid-body\">\r\n");
      out.write("\t");

   // Validar sesion
    Cookie[] MenuCookies = request.getCookies();
    
    String MenuUsername = null;
    String MenuUserID = null;
    String MenuRole = null;
    
    if (MenuCookies != null) {
        for (Cookie cookie : MenuCookies) {
            if ("username".equals(cookie.getName())) {
            	MenuUsername = cookie.getValue();
            } else if ("userID".equals(cookie.getName())) {
            	MenuUserID = cookie.getValue();
            } else if ("role".equals(cookie.getName())) {
            	MenuRole = cookie.getValue();
            }
        }
    }
    if (MenuUsername == null || MenuUserID == null || MenuRole == null || !"Usuario".equals(MenuRole)) {
        response.sendRedirect("Login.jsp"); 
        return;
    }


      out.write("\r\n");
      out.write("<section class=\"menu\">\r\n");
      out.write("    <navbar>\r\n");
      out.write("        <a href=\"InicioUsuario.jsp\">Incio</a>\r\n");
      out.write("\t\t<a href= \"ServletCuenta?Param=Transferencia\" >Nueva Transferencia</a>\r\n");
      out.write("\t\t<a href= \"ServletCuenta?Param=Prestamo\">Nuevo Prestamo</a>\r\n");
      out.write("\t\t<a href=\"ServletPrestamo?Param=listarPrestamos\">Mis Prestamos</a>\r\n");
      out.write("\t\t<a href=\"ServletCliente?Param=MostrarDatosPersonales\">Mi Perfil</a>\r\n");
      out.write("    </navbar>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t<p> ");
      out.print( MenuUsername );
      out.write(" </p>\r\n");
      out.write("    \t<a href=\"ServletSesion\">Cerrar Sesion</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>");
      out.write('\r');
      out.write('\n');
      out.write('	');

		Cookie[] cookies = request.getCookies();
		String userID = null;
		if (cookies != null) {
			for (Cookie cookie : cookies) {
				if ("userID".equals(cookie.getName())) {
					userID = cookie.getValue();
				}
			}
		}

		if (session.getAttribute("listaCu") == null) {
			response.sendRedirect("ServletCuenta?Param=Prestamo");
		}

		List<Cuenta> lista = (List<Cuenta>) session.getAttribute("listaCu");
	
      out.write("\r\n");
      out.write("\t<main>\r\n");
      out.write("\t<h1>Solicitar Prestamo</h1>\r\n");
      out.write("\t");

		if (lista == null || lista.isEmpty()) {
	
      out.write("\r\n");
      out.write("\t<p>No tienes cuentas para solicitar un prestamo.</p>\r\n");
      out.write("\t");

		} else {
        if (request.getAttribute("mensajeError") != null) {
    
      out.write("\r\n");
      out.write("        <p style=\"color: red; text-align: center;\">");
      out.print( request.getAttribute("mensajeError") );
      out.write("</p>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<form method=\"POST\" action=\"ServletPrestamo\"\r\n");
      out.write("\t\tonsubmit=\"return handleForm()\">\r\n");
      out.write("\t\t<label>Monto</label> <input name=\"monto\" id=\"monto\" type=\"text\" /> <span\r\n");
      out.write("\t\t\tid=\"error-monto\" style=\"color: red;\"></span> <br> <br> <label>Cuotas</label>\r\n");
      out.write("\t\t<select name=\"cuotas\" id=\"cuotas\">\r\n");
      out.write("\t\t\t<option value=\"\" selected disabled>Seleccionar Cuotas</option>\r\n");
      out.write("\t\t\t<option value=\"3\">3 Cuotas (10% interés)</option>\r\n");
      out.write("\t\t\t<option value=\"6\">6 Cuotas (20% interés)</option>\r\n");
      out.write("\t\t\t<option value=\"12\">12 Cuotas (40% interés)</option>\r\n");
      out.write("\t\t</select> <span id=\"error-cuotas\" style=\"color: red;\"></span> <br> <br>\r\n");
      out.write("\t\t<label> Seleccione cuenta <select name=\"cuenta\" id=\"cuenta\">\r\n");
      out.write("\t\t\t\t<option value=\"\" selected disabled>Seleccione una cuenta</option>\r\n");
      out.write("\t\t\t\t");

					for (Cuenta c : lista) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<option value=");
      out.print(c.getNroCuenta());
      out.write('>');
      out.print(c.getNroCuenta() + " - " + c.getTipoCuenta().getDescripcion() + " ($" + c.getSaldo() + ")");
      out.write("</option>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t</select>\r\n");
      out.write("\t\t</label> <span id=\"error-cuenta\" style=\"color: red;\"></span> <br> <br>\r\n");
      out.write("\t\t<br> <input type=\"submit\" name=\"SolicitarPrestamo\"\r\n");
      out.write("\t\t\tvalue=\"Solicitar Prestamo\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction handleForm(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlet valido = true;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// Validación del monto\r\n");
      out.write("\t\t\tconst monto = document.getElementById(\"monto\");\r\n");
      out.write("\t\t\tconst errorMonto = document.getElementById(\"error-monto\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (!monto.value.trim()) {\r\n");
      out.write("\t\t\t    errorMonto.textContent = \"Este campo es obligatorio.\";\r\n");
      out.write("\t\t\t    valido = false;\r\n");
      out.write("\t\t\t} else if (!/^\\d+(\\.\\d{1,2})?$/.test(monto.value.trim())) {\r\n");
      out.write("\t\t\t    errorMonto.textContent = \"El monto debe ser un número positivo con hasta 2 decimales.\";\r\n");
      out.write("\t\t\t    valido = false;\r\n");
      out.write("\t\t\t} else if (parseFloat(monto.value.trim()) > 50000) {\r\n");
      out.write("\t\t\t    errorMonto.textContent = \"El monto no puede ser mayor a $50,000.\";\r\n");
      out.write("\t\t\t    valido = false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t    errorMonto.textContent = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// Validación de las cuotas\r\n");
      out.write("\t\t\tconst cuotasSelect = document.getElementById(\"cuotas\");\r\n");
      out.write("\t\t\tconst errorCuotas = document.getElementById(\"error-cuotas\");\r\n");
      out.write("\t\t\tif (!cuotasSelect.value) {\r\n");
      out.write("\t\t\t    errorCuotas.textContent = \"Debe seleccionar una opción.\";\r\n");
      out.write("\t\t\t    valido = false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t    errorCuotas.textContent = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// Validación de la cuenta\r\n");
      out.write("\t\t\tconst cuentaSelect = document.getElementById(\"cuenta\");\r\n");
      out.write("\t\t\tconst errorCuenta = document.getElementById(\"error-cuenta\");\r\n");
      out.write("\t\t\tif (!cuentaSelect.value) {\r\n");
      out.write("\t\t\t    errorCuenta.textContent = \"Debe seleccionar una cuenta.\";\r\n");
      out.write("\t\t\t    valido = false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t    errorCuenta.textContent = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// Evitar el envío si hay errores\r\n");
      out.write("\t\t\tif (!valido) {\r\n");
      out.write("\t\t\t    event.preventDefault();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("</script> ");

 	}
 
      out.write(' ');

 	if (request.getAttribute("estado") != null) {
 
      out.write("\r\n");
      out.write("\t<p>\r\n");
      out.write("\t\tEstado:\r\n");
      out.write("\t\t");
      out.print(((Boolean) request.getAttribute("estado")) ? "Prestamo solicitado con exito" : "Ocurrio un error.");
      out.write("\r\n");
      out.write("\t</p>\r\n");
      out.write("\t");

		}
	
      out.write(" </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
