/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2024-12-12 13:12:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import entidad.*;
import negocioImpl.ClienteNegImpl;
import negocio.ClienteNeg;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.List;

public final class EditarClienteAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./MenuAdmin.jsp", Long.valueOf(1733984782229L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("entidad");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("negocioImpl.ClienteNegImpl");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("negocio.ClienteNeg");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Editar usuario</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=grid-body>\r\n");
      out.write("    ");

    	if(request.getAttribute("cliente") == null && session.getAttribute("cliente") == null){
    		response.sendRedirect("ServletCliente?Param=listarClientes");
    		return;
    	}
    	
        Cliente cliente = (Cliente)request.getAttribute("cliente");
        
        String fecha = null;
        
        if(session.getAttribute("cliente") != null){
        	cliente = (Cliente)session.getAttribute("cliente");
        	fecha = cliente.getFechaNacimientoString();
        }
    
   		String [] provs = {	"Buenos Aires","Catamarca","Chaco","Chubut","Córdoba","Corrientes","Entre Ríos","Formosa","Jujuy","La Pampa","La Rioja","Mendoza","Misiones",
		"Neuquén","Río Negro","Salta","San Juan","San Luis","Santa Cruz","Santa Fe","Santiago del Estero","Tierra del Fuego","Tucumán"};
   
   		String provCliente = cliente.getProvincia();
    
      out.write('\r');
      out.write('\n');

   // Validar sesion
    Cookie[] cookies = request.getCookies();
    
    String username = null;
    String userID = null;
    String role = null;
    
    if (cookies != null) {
        for (Cookie cookie : cookies) {
            if ("username".equals(cookie.getName())) {
                username = cookie.getValue();
            } else if ("userID".equals(cookie.getName())) {
                userID = cookie.getValue();
            } else if ("role".equals(cookie.getName())) {
                role = cookie.getValue();
            }
        }
    }
    if (username == null || userID == null || role == null || !"Admin".equals(role)) {
        response.sendRedirect("Login.jsp"); 
        return;
    }


      out.write("\r\n");
      out.write("<section class=\"menu\">\r\n");
      out.write("    <navbar>\r\n");
      out.write("        <a href=\"AltaClienteAdmin.jsp\">Agregar Cliente</a>\r\n");
      out.write("        <a href=\"AltaCuentaAdmin.jsp\">Agregar Cuenta</a>\r\n");
      out.write("        <a href=\"ServletCliente?Param=listarClientes\">ABML Clientes</a>\r\n");
      out.write("        <a href=\"ServletCuenta?Param=listarCuentas\">ABML Cuentas</a>\r\n");
      out.write("        <a href=\"ServletPrestamo?Param=listarPrestamos\">Listado Prestamos</a>\r\n");
      out.write("        <a href=\"ServletEstadistico\">Informes estadísticos</a>\r\n");
      out.write("    </navbar>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t<p> ");
      out.print( role + "  -  " + username );
      out.write(" </p>\r\n");
      out.write("    \t<a href=\"ServletSesion\">Cerrar Sesion</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("    <h1>Editar Cliente</h1>\r\n");
      out.write("    <form action=\"ServletCliente\" method=\"post\" onsubmit=\"return handleForm(event)\">\r\n");
      out.write("        <input type=\"hidden\" name=\"idCliente\" value=\"");
      out.print( cliente.getIdCliente() );
      out.write("\" />\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"dni\">DNI:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\"  type=\"number\" id=\"dni\" name=\"txtDni\" value=\"");
      out.print( cliente.getDni() );
      out.write("\">\r\n");
      out.write("                    <span class=\"error\" id=\"error-dni\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"cuil\">CUIL:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\"  type=\"text\" id=\"cuil\" name=\"txtCuil\" value=\"");
      out.print( cliente.getCuil() );
      out.write("\">\r\n");
      out.write("                    <span class=\"error\" id=\"error-cuil\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"nombre\">Nombre:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\"  type=\"text\" id=\"nombre\" name=\"txtNombre\" value=\"");
      out.print( cliente.getNombre() );
      out.write("\">\r\n");
      out.write("                    <span class=\"error\" id=\"error-nombre\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"apellido\">Apellido:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\"  type=\"text\" id=\"apellido\" name=\"txtApellido\" value=\"");
      out.print( cliente.getApellido() );
      out.write("\">\r\n");
      out.write("                    <span class=\"error\" id=\"error-apellido\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"sexo\">Sexo:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
 char sexo = cliente.getSexo(); 
      out.write("\r\n");
      out.write("                    <label for=\"H\">\r\n");
      out.write("                        <input type=\"radio\" id=\"M\" ");
      out.print( sexo == 'M' ? "checked" : "" );
      out.write(" name=\"txtSexo\" value=\"M\">\r\n");
      out.write("                        Hombre\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <label for=\"M\">\r\n");
      out.write("                        <input type=\"radio\" id=\"F\" ");
      out.print( sexo == 'F' ? "checked" : "" );
      out.write(" name=\"txtSexo\" value=\"F\">\r\n");
      out.write("                        Mujer\r\n");
      out.write("                    </label>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"nacionalidad\">Nacionalidad:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\"  type=\"text\" id=\"nacionalidad\" name=\"txtNacionalidad\" value=\"");
      out.print( cliente.getNacionalidad() );
      out.write("\">\r\n");
      out.write("                    <span class=\"error\" id=\"error-nacionalidad\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"fecha_nacimiento\">Fecha de Nacimiento:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input  type=\"date\" id=\"fecha_nacimiento\" name=\"txtFecha_Nacimiento\" value=\"");
      out.print( fecha == null ? cliente.getFechaNacimiento() : fecha);
      out.write("\">\r\n");
      out.write("                    <span class=\"error\" id=\"error-fecha_nacimiento\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"direccion\">Dirección:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\"  type=\"text\" id=\"direccion\" name=\"txtDireccion\" value=\"");
      out.print( cliente.getDireccion() );
      out.write("\">\r\n");
      out.write("                    <span class=\"error\" id=\"error-direccion\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"localidad\">Localidad:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\"  type=\"text\" id=\"localidad\" name=\"txtLocalidad\" value=\"");
      out.print( cliente.getLocalidad() );
      out.write("\">\r\n");
      out.write("                    <span class=\"error\" id=\"error-localidad\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"provincia\">Provincia:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <select id=\"provincia\" name=\"ddlProvincia\">\r\n");
      out.write("                        <option value=\"\" ");
      out.print( provCliente == "" ? "selected" : "" );
      out.write(" disabled>Seleccione una provincia</option>\r\n");
      out.write("                        ");
 for(String p : provs) { 
      out.write("\r\n");
      out.write("                        <option ");
      out.print( provCliente == p ? "selected" : "" );
      out.write(" value=");
      out.print( p );
      out.write(' ');
      out.write('>');
      out.print( p );
      out.write("</option>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <span id=\"error-provincia\" class=\"error\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"email\">Email:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\"  type=\"text\" id=\"email\" name=\"txtEmail\" value=\"");
      out.print( cliente.getEmail() );
      out.write("\">\r\n");
      out.write("                    <span id=\"error-email\" class=\"error\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"telefono\">Teléfono:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\"  type=\"text\" id=\"telefono\" name=\"txtTelefono\" value=\"");
      out.print( cliente.getTelefono() );
      out.write("\">\r\n");
      out.write("                    <span id=\"error-telefono\" class=\"error\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"usuario\">Usuario:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input readonly disabled class=\"input\" type=\"text\" id=\"usuario-readonly\" name=\"usuario-readonly\" value=\"");
      out.print( cliente.getUsuario() );
      out.write("\">\r\n");
      out.write("                    <span id=\"error-usuario\" class=\"error\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><label for=\"clave\">Clave:</label></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <input class=\"input\" type=\"text\" id=\"clave\" name=\"txtClave\" value=\"");
      out.print( cliente.getClave() );
      out.write("\">\r\n");
      out.write("                    <span id=\"error-clave\" class=\"error\" style=\"color: red;\"></span>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            \r\n");
      out.write("            <tr>\r\n");
      out.write("                <td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("                \t<input type=\"hidden\" name=\"dni-anterior\" value=\"");
      out.print( cliente.getDni() );
      out.write("\">\r\n");
      out.write("                \t<input type=\"hidden\" name=\"cuil-anterior\" value=\"");
      out.print( cliente.getCuil() );
      out.write("\">\r\n");
      out.write("                \t<input type=\"hidden\" name=\"id\" value=\"");
      out.print( cliente.getIdCliente() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"txtUsuario\" id=\"usuario\" name=\"usuario\" value=\"");
      out.print( cliente.getUsuario() );
      out.write("\">\t\r\n");
      out.write("                    <input type=\"submit\" name=\"btnConfirmarEdicion\" value=\"Aceptar\">\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                \t<input type=\"submit\" name=\"btnCancelarEdicion\" value=\"Cancelar\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("    </form>\r\n");
      out.write("   \t");

    Respuesta res = (Respuesta) session.getAttribute("EstadoCliente");
	   if (res != null) {
	
      out.write("\r\n");
      out.write("\t   <p style=\"color: ");
      out.print( res.isEstado() ? "green" : "red" );
      out.write("\">\r\n");
      out.write("\t       ");
      out.print( res.getMensaje() );
      out.write("\r\n");
      out.write("\t   </p>\r\n");
      out.write("\t");

    session.removeAttribute("EstadoCliente");
	session.removeAttribute("cliente");
}

      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\tfunction handleForm(event) {\r\n");
      out.write("\t          if (event.submitter.value === \"Cancelar\") {\r\n");
      out.write("\t              return true;\r\n");
      out.write("\t          }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlet valido = true;\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet errores = document.querySelectorAll(\".error\");\r\n");
      out.write("\t\t\tfor (let i = 0; i < errores.length; i++) {\r\n");
      out.write("\t\t\t\terrores[i].textContent = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Validar campos obligatorios\r\n");
      out.write("\r\n");
      out.write("\t\t\tlet textInputs = document.querySelectorAll(\".input\");\r\n");
      out.write("\t\t\tfor (let i = 0; i < textInputs.length; i++) {\r\n");
      out.write("\t\t\t\tconst id = textInputs[i].id;\r\n");
      out.write("\t\t\t\tconst campo = document.getElementById(id);\r\n");
      out.write("\t\t\t\tif (!campo.value.trim()) {\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"error-\" + id).textContent = \"Este campo es obligatorio.\";\r\n");
      out.write("\t\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tconst ID = document.getElementById(\"dni\").value.trim();\r\n");
      out.write("\t\t\tif(ID.length != 8){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-dni\").textContent = \"el DNI debe tener 8 digitos.\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconst cuil = document.getElementById(\"cuil\").value.trim();\r\n");
      out.write("\t\t\tconst cuilRegex = /^\\d{2}-\\d{8}-\\d{1}$/ ;\r\n");
      out.write("\t\t\tif (!cuilRegex.test(cuil)) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-cuil\").textContent = \"El cuil debe estar en formato xx-xxxxxxxx-x\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// Validar Fecha de Nacimiento (mayor a 18 años)\r\n");
      out.write("\t\t\tconst fechaNacimiento = document.getElementById(\"fecha_nacimiento\").value;\r\n");
      out.write("\t\t\tconst hoy = new Date();\r\n");
      out.write("\t\t\tconst fechaMinima = new Date(hoy.getFullYear() - 18,\r\n");
      out.write("\t\t\t\t\thoy.getMonth(), hoy.getDate());\r\n");
      out.write("\t\t\tif (new Date(fechaNacimiento) > fechaMinima) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-fecha-nacimiento\").textContent = \"Debe ser mayor de 18 años.\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Validar Email (formato correcto)\r\n");
      out.write("\t\t\tconst email = document.getElementById(\"email\").value.trim();\r\n");
      out.write("\t\t\tconst emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\r\n");
      out.write("\t\t\tif (!emailRegex.test(email)) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-email\").textContent = \"Debe ingresar un email válido.\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconst clave = document.getElementById(\"clave\").value.trim();\r\n");
      out.write("\t\t\tif(clave.length < 3){\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"error-clave\").textContent = \"La clave debe tener al menos 4 caracteres.\";\r\n");
      out.write("\t\t\t\tvalido = false;\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn valido;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
