/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2024-12-12 06:26:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import entidad.*;

public final class ListarClientesAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./MenuAdmin.jsp", Long.valueOf(1733984782229L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("entidad");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Lista de Clientes</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"grid-body\">\r\n");
      out.write("\t");

   // Validar sesion
    Cookie[] cookies = request.getCookies();
    
    String username = null;
    String userID = null;
    String role = null;
    
    if (cookies != null) {
        for (Cookie cookie : cookies) {
            if ("username".equals(cookie.getName())) {
                username = cookie.getValue();
            } else if ("userID".equals(cookie.getName())) {
                userID = cookie.getValue();
            } else if ("role".equals(cookie.getName())) {
                role = cookie.getValue();
            }
        }
    }
    if (username == null || userID == null || role == null || !"Admin".equals(role)) {
        response.sendRedirect("Login.jsp"); 
        return;
    }


      out.write("\r\n");
      out.write("<section class=\"menu\">\r\n");
      out.write("    <navbar>\r\n");
      out.write("        <a href=\"AltaClienteAdmin.jsp\">Agregar Cliente</a>\r\n");
      out.write("        <a href=\"AltaCuentaAdmin.jsp\">Agregar Cuenta</a>\r\n");
      out.write("        <a href=\"ServletCliente?Param=listarClientes\">ABML Clientes</a>\r\n");
      out.write("        <a href=\"ServletCuenta?Param=listarCuentas\">ABML Cuentas</a>\r\n");
      out.write("        <a href=\"ServletPrestamo?Param=listarPrestamos\">Listado Prestamos</a>\r\n");
      out.write("        <a href=\"ServletEstadistico\">Informes estadísticos</a>\r\n");
      out.write("    </navbar>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t<p> ");
      out.print( role + "  -  " + username );
      out.write(" </p>\r\n");
      out.write("    \t<a href=\"ServletSesion\">Cerrar Sesion</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("\t<main>\r\n");
      out.write("\t<h1>Lista de Clientes</h1>\r\n");
      out.write("\r\n");
      out.write("\t<form action=\"ServletCliente\" method=\"get\"\r\n");
      out.write("\t\tonsubmit=\"return validarFiltro(event);\">\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<label for=\"filtro\">Seleccionar Filtro:</label> <select name=\"filtro\"\r\n");
      out.write("\t\t\t\tid=\"filtro\" onchange=\"mostrarCampoFiltro(this.value)\">\r\n");
      out.write("\t\t\t\t<option value=\"0\">Seleccione</option>\r\n");
      out.write("\t\t\t\t<option value=\"id\">ID de Cliente</option>\r\n");
      out.write("\t\t\t\t<option value=\"nombre\">Nombre</option>\r\n");
      out.write("\t\t\t\t<option value=\"apellido\">Apellido</option>\r\n");
      out.write("\t\t\t</select> <span class=\"error\" id=\"error-filtro\" style=\"color: red;\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"campoFiltro\" style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"txtFiltro\" id=\"txtFiltro\"\r\n");
      out.write("\t\t\t\tplaceholder=\"Seleccione filtro\" style=\"width: 247px;\"> <span\r\n");
      out.write("\t\t\t\tclass=\"error\" id=\"error-txtFiltro\" style=\"color: red;\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"margin-top: 10px;\">\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"Param\" value=\"filtrarClientes\">Filtrar</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" name=\"Param\" value=\"listarClientes\">Eliminar\r\n");
      out.write("\t\t\t\tFiltros</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script>\r\n");
      out.write("    function mostrarCampoFiltro(filtro) {\r\n");
      out.write("        const campoFiltro = document.getElementById('campoFiltro');\r\n");
      out.write("        const txtFiltro = document.getElementById('txtFiltro');\r\n");
      out.write("\r\n");
      out.write("        switch (filtro) {\r\n");
      out.write("            case 'id':\r\n");
      out.write("                txtFiltro.placeholder = \"Ingrese el ID del cliente\";\r\n");
      out.write("                break;\r\n");
      out.write("            case 'nombre':\r\n");
      out.write("                txtFiltro.placeholder = \"Ingrese el Nombre del cliente\";\r\n");
      out.write("                break;\r\n");
      out.write("            case 'apellido':\r\n");
      out.write("                txtFiltro.placeholder = \"Ingrese el Apellido del cliente\";\r\n");
      out.write("                break;\r\n");
      out.write("            default:\r\n");
      out.write("                txtFiltro.placeholder = \"Seleccione filtro\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function validarFiltro(event) {\r\n");
      out.write(" \r\n");
      out.write("          if (event.submitter.value === \"listarClientes\") {\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("          }\r\n");
      out.write("        let valido = true;\r\n");
      out.write("\r\n");
      out.write("        document.getElementById(\"error-filtro\").textContent = \"\";\r\n");
      out.write("        document.getElementById(\"error-txtFiltro\").textContent = \"\";\r\n");
      out.write("\r\n");
      out.write("        const filtro = document.getElementById(\"filtro\").value;\r\n");
      out.write("        const txtFiltro = document.getElementById(\"txtFiltro\").value;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        if (filtro === \"0\") {\r\n");
      out.write("            document.getElementById(\"error-filtro\").textContent = \"Debe seleccionar un filtro.\";\r\n");
      out.write("            valido = false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        if (txtFiltro.trim() === \"\") {\r\n");
      out.write("            document.getElementById(\"error-txtFiltro\").textContent = \"Debe ingresar un valor para el filtro.\";\r\n");
      out.write("            valido = false;\r\n");
      out.write("        }else if (filtro === 'id' && isNaN(Number(txtFiltro.trim()))) {\r\n");
      out.write("            document.getElementById(\"error-txtFiltro\").textContent = \"El ID debe ser un número.\";\r\n");
      out.write("            valido = false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        return valido; \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function confirmar(event){\r\n");
      out.write("    \t\r\n");
      out.write("    \tif (event.submitter.value === \"Eliminar\") {\r\n");
      out.write("    \t\tif(confirm(\"¿Quieres eliminar este usuario?\")) return true;\r\n");
      out.write("    \t\telse{\r\n");
      out.write("    \t\t\treturn false;\r\n");
      out.write("    \t\t}\r\n");
      out.write("          }\r\n");
      out.write("    \t\r\n");
      out.write("    \treturn true;\r\n");
      out.write("    }\r\n");
      out.write("</script> ");

    	List<Cliente> lista = (List<Cliente>) request.getAttribute("listaCl");
		if(lista == null){
			response.sendRedirect("ServletCliente?Param=listarClientes");
			return;
		}
        if (lista == null || lista.isEmpty()) {
    
      out.write("\r\n");
      out.write("\t<p>No hay clientes disponibles.</p>\r\n");
      out.write("\t");

        } else {
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table border=\"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>ID Cliente</th>\r\n");
      out.write("\t\t\t<th>DNI</th>\r\n");
      out.write("\t\t\t<th>CUIL</th>\r\n");
      out.write("\t\t\t<th>Nombre</th>\r\n");
      out.write("\t\t\t<th>Apellido</th>\r\n");
      out.write("\t\t\t<th>Sexo</th>\r\n");
      out.write("\t\t\t<th>Nacionalidad</th>\r\n");
      out.write("\t\t\t<th>Fecha de Nacimiento</th>\r\n");
      out.write("\t\t\t<th>Direccion</th>\r\n");
      out.write("\t\t\t<th>Localidad</th>\r\n");
      out.write("\t\t\t<th>Provincia</th>\r\n");
      out.write("\t\t\t<th>Email</th>\r\n");
      out.write("\t\t\t<th>Telefono</th>\r\n");
      out.write("\t\t\t<th>Usuario</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t");

            for (Cliente c : lista) {
        
      out.write("\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getIdCliente() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getDni() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getCuil() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getNombre() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getApellido() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getSexo() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getNacionalidad() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getFechaNacimiento() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getDireccion() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getLocalidad() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getProvincia() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getEmail() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getTelefono() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( c.getUsuario() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<form action=\"ServletCliente\" method=\"post\" onsubmit=\"return confirmar(event)\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"idCliente\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print( c.getIdCliente() );
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" name=\"btnEditar\" value=\"Editar\">Editar</button>\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" name=\"btnEliminar\" value=\"Eliminar\">Eliminar</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

            }
        
      out.write("\r\n");
      out.write("\t</table>\r\n");
      out.write(" \t");

    Respuesta res = (Respuesta) session.getAttribute("EstadoCliente");
	   if (res != null) {
	
      out.write("\r\n");
      out.write("\t   <p style=\"color: ");
      out.print( res.isEstado() ? "green" : "red" );
      out.write("\">\r\n");
      out.write("\t       ");
      out.print( res.getMensaje() );
      out.write("\r\n");
      out.write("\t   </p>\r\n");
      out.write("\t");

    session.removeAttribute("EstadoCliente");
}

      out.write('\r');
      out.write('\n');
      out.write('	');

        }
    
      out.write(' ');
 
    int paginaActual = (int) request.getAttribute("paginaActual");
    int totalPaginas = (int) request.getAttribute("totalPaginas");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
 if (paginaActual > 1) { 
      out.write("\r\n");
      out.write("\t\t<a\r\n");
      out.write("\t\t\thref=\"ServletCliente?Param=listarClientes&pagina=");
      out.print( paginaActual - 1 );
      out.write("\">Anterior</a>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
 for (int i = 1; i <= totalPaginas; i++) { 
      out.write("\r\n");
      out.write("\t\t");
 if (i == paginaActual) { 
      out.write("\r\n");
      out.write("\t\t<strong>");
      out.print( i );
      out.write("</strong>\r\n");
      out.write("\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t<a href=\"ServletCliente?Param=listarClientes&pagina=");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</a>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
 if (paginaActual < totalPaginas) { 
      out.write("\r\n");
      out.write("\t\t<a\r\n");
      out.write("\t\t\thref=\"ServletCliente?Param=listarClientes&pagina=");
      out.print( paginaActual + 1 );
      out.write("\">Siguiente</a>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
