/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2024-12-12 06:46:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import entidad.*;

public final class ListarCuentasAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./MenuAdmin.jsp", Long.valueOf(1733984782229L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("entidad");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Lista Cuentas</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"grid-body\">\r\n");

   // Validar sesion
    Cookie[] cookies = request.getCookies();
    
    String username = null;
    String userID = null;
    String role = null;
    
    if (cookies != null) {
        for (Cookie cookie : cookies) {
            if ("username".equals(cookie.getName())) {
                username = cookie.getValue();
            } else if ("userID".equals(cookie.getName())) {
                userID = cookie.getValue();
            } else if ("role".equals(cookie.getName())) {
                role = cookie.getValue();
            }
        }
    }
    if (username == null || userID == null || role == null || !"Admin".equals(role)) {
        response.sendRedirect("Login.jsp"); 
        return;
    }


      out.write("\r\n");
      out.write("<section class=\"menu\">\r\n");
      out.write("    <navbar>\r\n");
      out.write("        <a href=\"AltaClienteAdmin.jsp\">Agregar Cliente</a>\r\n");
      out.write("        <a href=\"AltaCuentaAdmin.jsp\">Agregar Cuenta</a>\r\n");
      out.write("        <a href=\"ServletCliente?Param=listarClientes\">ABML Clientes</a>\r\n");
      out.write("        <a href=\"ServletCuenta?Param=listarCuentas\">ABML Cuentas</a>\r\n");
      out.write("        <a href=\"ServletPrestamo?Param=listarPrestamos\">Listado Prestamos</a>\r\n");
      out.write("        <a href=\"ServletEstadistico\">Informes estadísticos</a>\r\n");
      out.write("    </navbar>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t<p> ");
      out.print( role + "  -  " + username );
      out.write(" </p>\r\n");
      out.write("    \t<a href=\"ServletSesion\">Cerrar Sesion</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function toggleInput() {\r\n");
      out.write("    const select = document.getElementById('filtro');\r\n");
      out.write("    const input = document.getElementById('txtFiltro');\r\n");
      out.write("    const btnFiltrar = document.getElementById('btnFiltrar');\r\n");
      out.write("    \r\n");
      out.write("    if (select.value === \"0\") {\r\n");
      out.write("        input.value = \"\";          // Borrar el contenido del campo de texto\r\n");
      out.write("        input.disabled = true;     // Deshabilitar la edición del campo de texto\r\n");
      out.write("        btnFiltrar.disabled = true; // Deshabilitar el botón Filtrar\r\n");
      out.write("    } else {\r\n");
      out.write("        input.disabled = false;    // Habilitar la edición del campo de texto\r\n");
      out.write("        btnFiltrar.disabled = false; // Habilitar el botón Filtrar\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function handleForm(event){\r\n");
      out.write("\tif (event.submitter.value === \"listarCuentas\") {\r\n");
      out.write("        return true;\r\n");
      out.write("    }\r\n");
      out.write("\tlet valido = true;\r\n");
      out.write("\t\r\n");
      out.write("    const filtro = document.getElementById('filtro').value.trim();\r\n");
      out.write("    const txtFiltro = document.getElementById('txtFiltro');\r\n");
      out.write("    const valorFiltro = txtFiltro.value.trim();\r\n");
      out.write("\r\n");
      out.write("    const errorElement = document.getElementById('error-txtFiltro');\r\n");
      out.write("    if (errorElement) {\r\n");
      out.write("        errorElement.remove();\r\n");
      out.write("    }\r\n");
      out.write("\t\r\n");
      out.write("    // Validar según el filtro seleccionado\r\n");
      out.write("    switch (filtro) {\r\n");
      out.write("        case \"Nro_cuenta\":\r\n");
      out.write("        case \"Id_cliente\":\r\n");
      out.write("            if (!/^\\d+$/.test(valorFiltro)) {\r\n");
      out.write("                crearError(\"Debe ser un número entero.\");\r\n");
      out.write("                valido = false;\r\n");
      out.write("            }\r\n");
      out.write("            break;\r\n");
      out.write("        case \"Tipo_cuenta\":\r\n");
      out.write("            if (!/^[12]$/.test(valorFiltro)) {\r\n");
      out.write("                crearError(\"Debe ser 1 (Caja de Ahorro) o 2 (Cuenta Corriente).\");\r\n");
      out.write("                valido = false;\r\n");
      out.write("            }\r\n");
      out.write("            break;\r\n");
      out.write("        case \"Cbu\":\r\n");
      out.write("            if (!/^\\d{22}$/.test(valorFiltro)) {\r\n");
      out.write("                crearError(\"El CBU debe tener exactamente 22 dígitos.\");\r\n");
      out.write("                valido = false;\r\n");
      out.write("            }\r\n");
      out.write("            break;\r\n");
      out.write("        default:\r\n");
      out.write("            crearError(\"Seleccione un filtro válido.\");\r\n");
      out.write("            valido = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    return valido;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function confirmar(event){\r\n");
      out.write("\t\r\n");
      out.write("\tif (event.submitter.value === \"Eliminar\") {\r\n");
      out.write("\t\tif(confirm(\"¿Quieres eliminar este usuario?\")) return true;\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("      }\r\n");
      out.write("\t\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<main> \r\n");
      out.write("<h1>ABML Cuentas</h1>\r\n");
      out.write("<form action=\"ServletCuenta\" method=\"get\" onsubmit=\"return handleForm(event)\">\r\n");
      out.write("    <label for=\"filtro\">Seleccionar Filtro:</label> \r\n");
      out.write("    <select name=\"filtro\" id=\"filtro\" onchange=\"toggleInput()\">\r\n");
      out.write("        <option value=\"0\">Seleccione</option>\r\n");
      out.write("        <option value=\"Nro_cuenta\">Nro de cuenta</option>\r\n");
      out.write("        <option value=\"Id_cliente\">Id de cliente</option>\r\n");
      out.write("        <option value=\"Tipo_cuenta\">Tipo de cuenta</option>\r\n");
      out.write("        <option value=\"Cbu\">CBU</option>\r\n");
      out.write("    </select>\r\n");
      out.write("    <input type=\"text\" name=\"txtFiltro\" id=\"txtFiltro\" disabled> \r\n");
      out.write("    <br/>\r\n");
      out.write("    <button type=\"submit\" name=\"Param\" id=\"btnFiltrar\" value=\"filtrarCuentas\" disabled>Filtrar</button>\r\n");
      out.write("    <button type=\"submit\" name=\"Param\" value=\"listarCuentas\">Eliminar Filtros</button>\r\n");
      out.write("</form>\r\n");
      out.write(" \t");

 		List<Cuenta> lista = (List<Cuenta>) request.getAttribute("listaCu");
 		
 	
        if (lista == null || lista.isEmpty()) {
    
      out.write("\r\n");
      out.write("        <p>No hay cuentas disponibles.</p>\r\n");
      out.write("    ");

        } else {
    
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<table border=\"1\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Nro Cuenta</th>\r\n");
      out.write("\t\t\t<th>ID Cliente</th>\r\n");
      out.write("\t\t\t<th>Fecha de Creacion</th>\r\n");
      out.write("\t\t\t<th>Tipo de Cuenta</th>\r\n");
      out.write("\t\t\t<th>CBU</th>\r\n");
      out.write("\t\t\t<th>Saldo</th>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t");

            for (Cuenta c : lista) {
        
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("            <td>");
      out.print( c.getNroCuenta() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( c.getIdCliente() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( c.getFechaCreacion() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( c.getTipoCuenta().getDescripcion() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( c.getCbu() );
      out.write("</td>\r\n");
      out.write("            <td>");
      out.print( c.getSaldo() );
      out.write("</td>\r\n");
      out.write("            <td>\r\n");
      out.write("    \t\t\t<form action=\"ServletCuenta\" method=\"post\" onsubmit=\"return confirmar(event);\">\r\n");
      out.write("        \t\t\t<input type=\"hidden\" name=\"nroCuenta\" value=\"");
      out.print( c.getNroCuenta() );
      out.write("\" />\r\n");
      out.write("       \t\t \t\t<button type=\"submit\" name = \"btnEditar\" value=\"Editar\">Editar</button>\r\n");
      out.write("       \t\t \t\t<button type=\"submit\" name = \"btnEliminar\" value=\"Eliminar\">Eliminar</button>\r\n");
      out.write("    \t\t\t</form>\r\n");
      out.write("    \t\t</td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        ");
 
    Integer paginaActual = (Integer) request.getAttribute("paginaActual");
    Integer totalPaginas = (Integer) request.getAttribute("totalPaginas");

      out.write("\r\n");
      out.write("\r\n");

    if (paginaActual != null && totalPaginas != null && totalPaginas > 1) {

      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("    ");
 if (paginaActual > 1) { 
      out.write("\r\n");
      out.write("        <a href=\"ServletCuenta?Param=listarCuentas&pagina=");
      out.print( paginaActual - 1 );
      out.write("\">Anterior</a>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 for (int i = 1; i <= totalPaginas; i++) { 
      out.write("\r\n");
      out.write("        ");
 if (i == paginaActual) { 
      out.write("\r\n");
      out.write("            <strong>");
      out.print( i );
      out.write("</strong>\r\n");
      out.write("        ");
 } else { 
      out.write("\r\n");
      out.write("            <a href=\"ServletCuenta?Param=listarCuentas&pagina=");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</a>\r\n");
      out.write("        ");
 } 
      out.write("\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
 if (paginaActual < totalPaginas) { 
      out.write("\r\n");
      out.write("        <a href=\"ServletCuenta?Param=listarCuentas&pagina=");
      out.print( paginaActual + 1 );
      out.write("\">Siguiente</a>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");

    }

      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
