/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2024-12-12 04:51:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import entidad.*;

public final class MovimientosUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/./MenuUsuario.jsp", Long.valueOf(1733963303679L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("entidad");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Mis Movimientos</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"styles.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"grid-body\">\r\n");

   // Validar sesion
    Cookie[] MenuCookies = request.getCookies();
    
    String MenuUsername = null;
    String MenuUserID = null;
    String MenuRole = null;
    
    if (MenuCookies != null) {
        for (Cookie cookie : MenuCookies) {
            if ("username".equals(cookie.getName())) {
            	MenuUsername = cookie.getValue();
            } else if ("userID".equals(cookie.getName())) {
            	MenuUserID = cookie.getValue();
            } else if ("role".equals(cookie.getName())) {
            	MenuRole = cookie.getValue();
            }
        }
    }
    if (MenuUsername == null || MenuUserID == null || MenuRole == null || !"Usuario".equals(MenuRole)) {
        response.sendRedirect("Login.jsp"); 
        return;
    }


      out.write("\r\n");
      out.write("<section class=\"menu\">\r\n");
      out.write("    <navbar>\r\n");
      out.write("        <a href=\"InicioUsuario.jsp\">Incio</a>\r\n");
      out.write("\t\t<a href= \"ServletCuenta?Param=Transferencia\" >Nueva Transferencia</a>\r\n");
      out.write("\t\t<a href= \"ServletCuenta?Param=Prestamo\">Nuevo Prestamo</a>\r\n");
      out.write("\t\t<a href=\"ServletPrestamo?Param=listarPrestamos\">Mis Prestamos</a>\r\n");
      out.write("\t\t<a href=\"ServletCliente?Param=MostrarDatosPersonales\">Mi Perfil</a>\r\n");
      out.write("    </navbar>\r\n");
      out.write("    <div>\r\n");
      out.write("    \t<p> ");
      out.print( MenuUsername );
      out.write(" </p>\r\n");
      out.write("    \t<a href=\"ServletSesion\">Cerrar Sesion</a>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>");
      out.write("\r\n");
      out.write("<main> \r\n");
      out.write("<h1>Mis Movimientos</h1>\r\n");
      out.write("\r\n");
      out.write("<form method=\"GET\" action=\"ServletCuenta\" onsubmit=\"return validateForm()\">\r\n");
      out.write("    <input type=\"hidden\" name=\"Param\" value=\"Movimientos\">\r\n");
      out.write("    <input type=\"hidden\" name=\"Nro\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.Nro}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("    <label for=\"minimo\">Mínimo:</label>\r\n");
      out.write("    <input type=\"number\" id=\"minimo\" name=\"minimo\" step=\"0.01\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.minimo != null ? param.minimo : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    <span id=\"error-minimo\" style=\"color: red;\"></span>\r\n");
      out.write("    \r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"maximo\">Máximo:</label>\r\n");
      out.write("    <input type=\"number\" id=\"maximo\" name=\"maximo\" step=\"0.01\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.maximo != null ? param.maximo : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("    <span id=\"error-maximo\" style=\"color: red;\"></span>\r\n");
      out.write("    \r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"submit\">Filtrar</button>\r\n");
      out.write("    <a href=\"ServletCuenta?Param=Movimientos&Nro=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.Nro}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Quitar Filtro</a>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function validateForm() {\r\n");
      out.write("    const minimo = document.getElementById(\"minimo\").value.trim();\r\n");
      out.write("    const maximo = document.getElementById(\"maximo\").value.trim();\r\n");
      out.write("    const errorMinimo = document.getElementById(\"error-minimo\");\r\n");
      out.write("    const errorMaximo = document.getElementById(\"error-maximo\");\r\n");
      out.write("\r\n");
      out.write("    let isValid = true;\r\n");
      out.write("\r\n");
      out.write("    errorMinimo.textContent = \"\";\r\n");
      out.write("    errorMaximo.textContent = \"\";\r\n");
      out.write("\r\n");
      out.write("    if (minimo === \"\") {\r\n");
      out.write("        errorMinimo.textContent = \"El valor mínimo es obligatorio.\";\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("    if (maximo === \"\") {\r\n");
      out.write("        errorMaximo.textContent = \"El valor máximo es obligatorio.\";\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Validar que mínimo no sea mayor que máximo\r\n");
      out.write("    if (minimo !== \"\" && maximo !== \"\" && parseFloat(minimo) > parseFloat(maximo)) {\r\n");
      out.write("        errorMaximo.textContent = \"El valor máximo debe ser mayor o igual al mínimo.\";\r\n");
      out.write("        isValid = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    return isValid;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write(" ");

    	String nro = (String)request.getParameter("Nro");
 		List<Movimiento> lista = (List<Movimiento>)request.getAttribute("listaMov");
        if (lista == null || lista.isEmpty()) {
    
      out.write("\r\n");
      out.write("        <p>No hay ningun movmiento.</p>\r\n");
      out.write("    ");

        } else {
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <table border=\"1\">\r\n");
      out.write("<tr>\r\n");
      out.write("<th>Fecha</th>\r\n");
      out.write("<th>Importe</th>\r\n");
      out.write("<th>Detalle</th>\r\n");
      out.write("<th>Tipo de Movimiento</th>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("        ");

            for (Movimiento m : lista) {
           
        
      out.write("\r\n");
      out.write("        <tr>\r\n");
      out.write("\t\t\t<td>");
      out.print( m.getFechaString() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( ( m.getImporte() > 0 ? "+" : "" ) + m.getImporte() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( m.getDetalle() );
      out.write("</td>\r\n");
      out.write("\t\t\t<td>");
      out.print( m.getTipoMovimiento().getDescripcion() );
      out.write("</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("        ");

            }
        
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");

        }
    
      out.write(" \r\n");
      out.write("    \r\n");
 
    int paginaActual = (int) request.getAttribute("paginaActualMovimientos");
    int totalPaginas = (int) request.getAttribute("totalPaginasMovimientos");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t");
 if (paginaActual > 1) { 
      out.write("\r\n");
      out.write("\t    <a\r\n");
      out.write("\t        href=\"ServletCuenta?Param=Movimientos&Nro=");
      out.print( nro );
      out.write("&pagina=");
      out.print( (paginaActual - 1) );
      out.write("\">  \r\n");
      out.write("\t\tAnterior\r\n");
      out.write("\t    </a>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
 for (int i = 1; i <= totalPaginas; i++) { 
      out.write("\r\n");
      out.write("\t\t\t");
 if (i == paginaActual) { 
      out.write("\r\n");
      out.write("\t\t\t<b>");
      out.print( i );
      out.write("</b>\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t<a href=\"ServletCuenta?Param=Movimientos&Nro=");
      out.print( nro );
      out.write("&pagina=");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</a>\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t");
 if (paginaActual < totalPaginas) { 
      out.write("\r\n");
      out.write("\t\t<a\r\n");
      out.write("\t\t\thref=\"ServletCuenta?Param=Movimientos&Nro=");
      out.print( nro );
      out.write("&&pagina=");
      out.print( paginaActual + 1 );
      out.write("\">Siguiente</a>\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
